# Generated by Django 6.0 on 2025-12-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeETG', models.CharField(max_length=20, unique=True, verbose_name='Код груза (ЕТСНГ)')),
                ('codeGNG', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код груза (ГНГ)')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование груза')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код станции')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WagonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код типа вагона')),
                ('name', models.CharField(max_length=120, verbose_name='Тип вагона')),
                ('capacity_tons', models.DecimalField(blank=True, decimal_places=2, help_text='Например: 68.00', max_digits=7, null=True, verbose_name='Грузоподъемность, т')),
            ],
            options={
                'verbose_name': 'Тип вагона',
                'verbose_name_plural': 'Типы вагонов',
                'ordering': ['name'],
            },
        ),
    ]
