# Generated by Django 6.0 on 2025-12-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railTarifs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='codeETG',
            new_name='etsng_code',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='codeGNG',
            new_name='gng_code',
        ),
    ]
