# Generated by Django 6.0 on 2025-12-22 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railTarifs', '0002_rename_codeetg_cargo_etsng_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fstate', models.PositiveSmallIntegerField(default=20, verbose_name='Код страны отправления')),
                ('tstate', models.PositiveSmallIntegerField(default=20, verbose_name='Код страны назначения')),
                ('modular', models.BooleanField(default=False, verbose_name='Сборная отправка (modular)')),
                ('empt', models.BooleanField(default=False, verbose_name='Порожняя отправка (empt)')),
                ('owner', models.BooleanField(default=False, verbose_name='Собственный/арендованный (owner)')),
                ('return_calc', models.BooleanField(default=False, verbose_name='Рассчитывать возврат (return)')),
                ('is_speed', models.BooleanField(default=True, verbose_name='Большая скорость (is_speed)')),
                ('is_cont_train', models.BooleanField(default=True, verbose_name='Контейнерный поезд (is_cont_train)')),
                ('route', models.BooleanField(default=True, verbose_name='Нитка маршрута (route)')),
                ('calc_date', models.DateField(blank=True, null=True, verbose_name='Дата расчёта (calc_date)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='railTarifs.cargo', verbose_name='Груз')),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queries_from', to='railTarifs.station', verbose_name='Станция отправления')),
                ('return_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queries_return', to='railTarifs.station', verbose_name='Станция возврата (return_st)')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queries_to', to='railTarifs.station', verbose_name='Станция назначения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_queries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('wagon_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='railTarifs.wagontype', verbose_name='Тип вагона')),
            ],
            options={
                'verbose_name': 'Запрос тарифа',
                'verbose_name_plural': 'Запросы тарифов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TariffResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=False, verbose_name='Успешно')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Итоговая ставка')),
                ('currency', models.CharField(blank=True, default='RUB', max_length=10, verbose_name='Валюта')),
                ('raw_xml', models.TextField(blank=True, verbose_name='Ответ API (XML)')),
                ('error_text', models.TextField(blank=True, verbose_name='Ошибка')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='railTarifs.tariffquery', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Результат расчёта',
                'verbose_name_plural': 'Результаты расчётов',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='TariffWagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='№ вагона (1..N)')),
                ('weight_kg', models.PositiveIntegerField(verbose_name='Вес, кг (w/wN)')),
                ('capacity_tons', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Г/п, т (gp/gpN)')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagons', to='railTarifs.tariffquery', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Вагон в отправке',
                'verbose_name_plural': 'Вагоны в отправке',
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('query', 'index'), name='uniq_wagon_index_per_query')],
            },
        ),
    ]
