# Generated by Django 6.0 on 2025-12-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railTarifs', '0003_tariffquery_tariffresult_tariffwagon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код страны')),
                ('name', models.CharField(max_length=120, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
    ]
