# Generated by Django 6.0 on 2025-12-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railTarifs', '0004_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='name',
            field=models.CharField(max_length=600, verbose_name='Наименование груза'),
        ),
        migrations.AlterField(
            model_name='wagontype',
            name='name',
            field=models.CharField(max_length=600, verbose_name='Тип вагона'),
        ),
    ]
